global:
  smtp_smarthost: 'smtp.gmail.com:25'
  smtp_from: '$MAIL_ACCOUNT'
  smtp_auth_username: '$MAIL_ACCOUNT'
  smtp_auth_password: '$MAIL_AUTH_TOKEN'

route:
  receiver: 'eca-admin'

receivers:
  - name: 'eca-admin'
    email_configs:
      - to: '$MAIL_RECEIVER_ACCOUNT'