global:
  scrape_interval: 30s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'eca-oauth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-oauth:8080']
  - job_name: 'eca-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-server-instance-1:8080', 'eca-server-instance-2:8080']
  - job_name: 'eca-mail'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-mail:8080']
  - job_name: 'eca-data-storage'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-data-storage:8080']
  - job_name: 'eca-web'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-web:8080']
  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8761']
  - job_name: 'zuul-gate'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['zuul-gate:8030']
  - job_name: 'evaluation-results-service'
    metrics_path: '/actuator/prometheus'
    scheme: https
    tls_config:
       insecure_skip_verify: true
    static_configs:
      - targets: ['evaluation-results-service:9443']