global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 'eca-oauth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-oauth:8080']
  - job_name: 'eca-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-server-instance-1:8080', 'eca-server-instance-2:8080']
  - job_name: 'eca-ers'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-ers:8080']
  - job_name: 'eca-mail'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-mail:8080']
  - job_name: 'eca-data-storage'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-data-storage:8080']
  - job_name: 'eca-web'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-web:8080']
  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8761']
  - job_name: 'zuul-gate'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['zuul-gate:8030']
  - job_name: 'eca-web-push'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eca-web-push:8099']
