{
 "title": "Eca - service dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Eca audit log 5xx errors / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-audit-log\",application=\"eca-server\"}[1m]) * 60) / 2",
     "legendFormat": "eca-server"
    },
    {
     "expr": "sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-audit-log\",application=\"eca-oauth\"}[1m]) * 60) / 2",
     "legendFormat": "eca-oauth"
    },
    {
     "expr": "sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-audit-log\",application=\"eca-data-storage\"}[1m]) * 60) / 2",
     "legendFormat": "eca-data-storage"
    }
   ]
  },
  {
   "title": "Eca mail 5xx errors / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-mail\",application=\"eca-server\"}[1m]) * 60) / 2",
     "legendFormat": "eca-server"
    },
    {
     "expr": "sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-mail\",application=\"eca-oauth\"}[1m]) * 60) / 2",
     "legendFormat": "eca-oauth"
    }
   ]
  },
  {
   "title": "Ers 5xx errors / min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-ers\",application=\"eca-server\"}[1m]) * 60) / 2",
     "legendFormat": "eca-server"
    }
   ]
  },
  {
   "title": "Mail error requests / min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(eca_mail_sending_message_error_total[1m]) * 60)",
     "legendFormat": "mail_error_requests"
    }
   ]
  }
 ]
}