--
-- PostgreSQL database dump
--

-- Dumped from database version 13.9 (Debian 13.9-1.pgdg110+1)
-- Dumped by pg_dump version 14.2

-- Started on 2023-06-30 22:14:48

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3077 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 203 (class 1259 OID 16464)
-- Name: audit_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    event_id character varying(255) NOT NULL,
    message text NOT NULL,
    initiator character varying(255) NOT NULL,
    event_type character varying(255) NOT NULL,
    group_code character varying(255) NOT NULL,
    group_title character varying(255),
    audit_code character varying(255) NOT NULL,
    audit_code_title character varying(255),
    event_date timestamp without time zone NOT NULL,
    correlation_id character varying(255)
);


ALTER TABLE public.audit_log OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 16456)
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 16441)
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16511)
-- Name: filter_dictionary; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.filter_dictionary (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.filter_dictionary OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16509)
-- Name: filter_dictionary_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.filter_dictionary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.filter_dictionary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16539)
-- Name: filter_dictionary_value; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.filter_dictionary_value (
    id bigint NOT NULL,
    label character varying(255) NOT NULL,
    value character varying(255) NOT NULL,
    filter_dictionary_id bigint NOT NULL
);


ALTER TABLE public.filter_dictionary_value OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16537)
-- Name: filter_dictionary_value_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.filter_dictionary_value ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.filter_dictionary_value_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 16518)
-- Name: filter_field; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.filter_field (
    id bigint NOT NULL,
    field_name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    field_order integer NOT NULL,
    filter_field_type character varying(255) NOT NULL,
    match_mode character varying(255) NOT NULL,
    filter_template_id bigint NOT NULL,
    filter_dictionary_id bigint,
    multiple boolean DEFAULT false
);


ALTER TABLE public.filter_field OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16516)
-- Name: filter_field_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.filter_field ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.filter_field_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16501)
-- Name: filter_template; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.filter_template (
    id bigint NOT NULL,
    template_name character varying(255) NOT NULL,
    template_type character varying(255) NOT NULL,
    created timestamp without time zone NOT NULL
);


ALTER TABLE public.filter_template OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 16499)
-- Name: filter_template_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.filter_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.filter_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 16484)
-- Name: global_filter_field; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.global_filter_field (
    id bigint NOT NULL,
    field_name character varying(255) NOT NULL,
    global_filter_template_id bigint NOT NULL
);


ALTER TABLE public.global_filter_field OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 16482)
-- Name: global_filter_field_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.global_filter_field ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.global_filter_field_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 16474)
-- Name: global_filter_template; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.global_filter_template (
    id bigint NOT NULL,
    filter_name character varying(255) NOT NULL,
    template_type character varying(255) NOT NULL
);


ALTER TABLE public.global_filter_template OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 16472)
-- Name: global_filter_template_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.global_filter_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.global_filter_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 16462)
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- TOC entry 3059 (class 0 OID 16464)
-- Dependencies: 203
-- Data for Name: audit_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audit_log (id, event_id, message, initiator, event_type, group_code, group_title, audit_code, audit_code_title, event_date, correlation_id) FROM stdin;
\.


--
-- TOC entry 3057 (class 0 OID 16456)
-- Dependencies: 201
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
1	roman.batygin@mail.ru	db/changelog/v0-init-schema.xml	2023-06-30 21:50:36.60941	1	EXECUTED	8:a3d354491071bf1899da0ff55cd58976	createSequence sequenceName=hibernate_sequence		\N	3.7.0	\N	\N	8136636355
2	roman.batygin@mail.ru	db/changelog/v0-init-schema.xml	2023-06-30 21:50:36.657116	2	EXECUTED	8:9f1fb12379dc6c885f3ee5ca7ce03441	createTable tableName=audit_log		\N	3.7.0	schema	\N	8136636355
create_global_filter_template	roman.batygin@mail.ru	classpath:db/../filter-template-changelog.xml	2023-06-30 21:50:36.724118	3	EXECUTED	8:cda8ce64a6a0ed0b153fc32329a6bbc6	createTable tableName=global_filter_template		\N	3.7.0	schema	\N	8136636355
create_global_filter_field	roman.batygin@mail.ru	classpath:db/../filter-template-changelog.xml	2023-06-30 21:50:36.772736	4	EXECUTED	8:208fa1a1dea8d771abc9ff8cbadf633a	createTable tableName=global_filter_field		\N	3.7.0	schema	\N	8136636355
create_filter_template	roman.batygin@mail.ru	classpath:db/../filter-template-changelog.xml	2023-06-30 21:50:36.853565	5	EXECUTED	8:eef92c0687a1a6dd158fd71ff3837ce3	createTable tableName=filter_template		\N	3.7.0	schema	\N	8136636355
create_filter_dictionary	roman.batygin@mail.ru	classpath:db/../filter-template-changelog.xml	2023-06-30 21:50:36.897054	6	EXECUTED	8:c70f4717adc271d0d4c4c6d6450884e8	createTable tableName=filter_dictionary		\N	3.7.0	schema	\N	8136636355
create_filter_field	roman.batygin@mail.ru	classpath:db/../filter-template-changelog.xml	2023-06-30 21:50:36.977683	7	EXECUTED	8:3b2b63d3773cd2af170a833724b21ca6	createTable tableName=filter_field		\N	3.7.0	schema	\N	8136636355
create_filter_dictionary_value	roman.batygin@mail.ru	classpath:db/../filter-template-changelog.xml	2023-06-30 21:50:37.028234	8	EXECUTED	8:d6f60bac76ab39d3dd5dbb02834e7cb3	createTable tableName=filter_dictionary_value		\N	3.7.0	schema	\N	8136636355
1	roman.batygin@mail.ru	db/changelog/v1-insert-filter-templates.xml	2023-06-30 21:50:37.041791	9	EXECUTED	8:fbff5761de7f019a13bb9c990c8680b6	insert tableName=global_filter_template; insert tableName=global_filter_field; insert tableName=global_filter_field; insert tableName=global_filter_field; insert tableName=global_filter_field; insert tableName=global_filter_field		\N	3.7.0	data	\N	8136636355
2	roman.batygin@mail.ru	db/changelog/v1-insert-filter-templates.xml	2023-06-30 21:50:37.052803	10	EXECUTED	8:6f9348f21396414d9a4986df357e2980	insert tableName=filter_dictionary; insert tableName=filter_dictionary_value; insert tableName=filter_dictionary_value; insert tableName=filter_dictionary_value		\N	3.7.0	data	\N	8136636355
3	roman.batygin@mail.ru	db/changelog/v1-insert-filter-templates.xml	2023-06-30 21:50:37.062977	11	EXECUTED	8:5653db8278f3f060bf406ece81e15481	insert tableName=filter_template; insert tableName=filter_field; insert tableName=filter_field; insert tableName=filter_field; insert tableName=filter_field		\N	3.7.0	data	\N	8136636355
1	roman.batygin@mail.ru	db/changelog/v2-add-correlation-id-column.xml	2023-06-30 21:50:37.072656	12	EXECUTED	8:6f8500b4dbeba1ab7116e43680f2a97f	addColumn tableName=audit_log		\N	3.7.0	schema	\N	8136636355
1	roman.batygin@mail.ru	db/changelog/v3-insert-correlation-id-in-filter-templates.xml	2023-06-30 21:50:37.096891	13	EXECUTED	8:ee0e775664f68489150bc4afcd695fde	insert tableName=global_filter_field		\N	3.7.0	data	\N	8136636355
2	roman.batygin@mail.ru	db/changelog/v3-insert-correlation-id-in-filter-templates.xml	2023-06-30 21:50:37.111672	14	EXECUTED	8:e85b45e64da5a1b673a58bc42f21e4ba	update tableName=filter_field		\N	3.7.0	data	\N	8136636355
3	roman.batygin@mail.ru	db/changelog/v3-insert-correlation-id-in-filter-templates.xml	2023-06-30 21:50:37.126681	15	EXECUTED	8:2062d3917b99a82047cad3511340007d	insert tableName=filter_field		\N	3.7.0	data	\N	8136636355
1	roman.batygin@mail.ru	db/changelog/v4-add-event-id-unique-idx.xml	2023-06-30 21:50:37.176152	16	EXECUTED	8:c1bdeecfed0609588b6e78e57291d1ea	addUniqueConstraint constraintName=audit_log_event_id_unique_idx, tableName=audit_log		\N	3.7.0	schema	\N	8136636355
1	roman.batygin@mail.ru	db/changelog/v5-insert-filter-templates.xml	2023-06-30 21:50:37.184246	17	EXECUTED	8:85239796437b717406e79df80c38a6a1	insert tableName=filter_dictionary_value		\N	3.7.0	data	\N	8136636355
change_correlation_id_match_mode	roman.batygin@mail.ru	db/changelog/v6-change-correlation-id-match-mode.xml	2023-06-30 21:50:37.201751	18	EXECUTED	8:501e54d6937a22f5abd6c148a3adc8d5	update tableName=filter_field		\N	3.7.0	data	\N	8136636355
\.


--
-- TOC entry 3056 (class 0 OID 16441)
-- Dependencies: 200
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- TOC entry 3067 (class 0 OID 16511)
-- Dependencies: 211
-- Data for Name: filter_dictionary; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.filter_dictionary (id, name) FROM stdin;
1	auditGroup
\.


--
-- TOC entry 3071 (class 0 OID 16539)
-- Dependencies: 215
-- Data for Name: filter_dictionary_value; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.filter_dictionary_value (id, label, value, filter_dictionary_id) FROM stdin;
1	Действия пользователя в личном кабинете	USER_PROFILE_ACTIONS	1
2	Действия с конфигурациями классификаторов	CLASSIFIERS_CONFIGURATIONS_ACTIONS	1
3	Действия с обучающими выборками	DATA_STORAGE_ACTIONS	1
4	Действия с заявками на построение моделей	EVALUATION_REQUESTS_ACTIONS	1
\.


--
-- TOC entry 3069 (class 0 OID 16518)
-- Dependencies: 213
-- Data for Name: filter_field; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.filter_field (id, field_name, description, field_order, filter_field_type, match_mode, filter_template_id, filter_dictionary_id, multiple) FROM stdin;
1	eventId	ID события	0	TEXT	LIKE	1	\N	f
2	groupCode	Группа событий	2	REFERENCE	EQUALS	1	1	f
3	initiator	Инициатор события	3	TEXT	LIKE	1	\N	f
4	eventDate	Дата события	4	DATE	RANGE	1	\N	t
5	correlationId	ID корреляции	1	TEXT	EQUALS	1	\N	f
\.


--
-- TOC entry 3065 (class 0 OID 16501)
-- Dependencies: 209
-- Data for Name: filter_template; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.filter_template (id, template_name, template_type, created) FROM stdin;
1	Фильтр событий аудита	AUDIT_LOG	2023-06-30 21:50:37.056314
\.


--
-- TOC entry 3063 (class 0 OID 16484)
-- Dependencies: 207
-- Data for Name: global_filter_field; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.global_filter_field (id, field_name, global_filter_template_id) FROM stdin;
1	eventId	1
2	message	1
3	initiator	1
4	groupTitle	1
5	codeTitle	1
6	correlationId	1
\.


--
-- TOC entry 3061 (class 0 OID 16474)
-- Dependencies: 205
-- Data for Name: global_filter_template; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.global_filter_template (id, filter_name, template_type) FROM stdin;
1	auditLogFilter	AUDIT_LOG
\.


--
-- TOC entry 3078 (class 0 OID 0)
-- Dependencies: 210
-- Name: filter_dictionary_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.filter_dictionary_id_seq', 1, false);


--
-- TOC entry 3079 (class 0 OID 0)
-- Dependencies: 214
-- Name: filter_dictionary_value_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.filter_dictionary_value_id_seq', 4, true);


--
-- TOC entry 3080 (class 0 OID 0)
-- Dependencies: 212
-- Name: filter_field_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.filter_field_id_seq', 5, true);


--
-- TOC entry 3081 (class 0 OID 0)
-- Dependencies: 208
-- Name: filter_template_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.filter_template_id_seq', 1, false);


--
-- TOC entry 3082 (class 0 OID 0)
-- Dependencies: 206
-- Name: global_filter_field_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.global_filter_field_id_seq', 6, true);


--
-- TOC entry 3083 (class 0 OID 0)
-- Dependencies: 204
-- Name: global_filter_template_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.global_filter_template_id_seq', 1, false);


--
-- TOC entry 3084 (class 0 OID 0)
-- Dependencies: 202
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hibernate_sequence', 1, false);


--
-- TOC entry 2907 (class 2606 OID 16559)
-- Name: audit_log audit_log_event_id_unique_idx; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_event_id_unique_idx UNIQUE (event_id);


--
-- TOC entry 2909 (class 2606 OID 16471)
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- TOC entry 2905 (class 2606 OID 16445)
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- TOC entry 2917 (class 2606 OID 16515)
-- Name: filter_dictionary filter_dictionary_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.filter_dictionary
    ADD CONSTRAINT filter_dictionary_pkey PRIMARY KEY (id);


--
-- TOC entry 2921 (class 2606 OID 16546)
-- Name: filter_dictionary_value filter_dictionary_value_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.filter_dictionary_value
    ADD CONSTRAINT filter_dictionary_value_pkey PRIMARY KEY (id);


--
-- TOC entry 2919 (class 2606 OID 16526)
-- Name: filter_field filter_field_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.filter_field
    ADD CONSTRAINT filter_field_pkey PRIMARY KEY (id);


--
-- TOC entry 2915 (class 2606 OID 16508)
-- Name: filter_template filter_template_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.filter_template
    ADD CONSTRAINT filter_template_pkey PRIMARY KEY (id);


--
-- TOC entry 2913 (class 2606 OID 16488)
-- Name: global_filter_field global_filter_field_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.global_filter_field
    ADD CONSTRAINT global_filter_field_pkey PRIMARY KEY (id);


--
-- TOC entry 2911 (class 2606 OID 16481)
-- Name: global_filter_template global_filter_template_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.global_filter_template
    ADD CONSTRAINT global_filter_template_pkey PRIMARY KEY (id);


--
-- TOC entry 2925 (class 2606 OID 16547)
-- Name: filter_dictionary_value fk_filter_dictionary_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.filter_dictionary_value
    ADD CONSTRAINT fk_filter_dictionary_id FOREIGN KEY (filter_dictionary_id) REFERENCES public.filter_dictionary(id);


--
-- TOC entry 2924 (class 2606 OID 16532)
-- Name: filter_field fk_filter_field_dictionary_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.filter_field
    ADD CONSTRAINT fk_filter_field_dictionary_id FOREIGN KEY (filter_dictionary_id) REFERENCES public.filter_dictionary(id);


--
-- TOC entry 2923 (class 2606 OID 16527)
-- Name: filter_field fk_filter_template_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.filter_field
    ADD CONSTRAINT fk_filter_template_id FOREIGN KEY (filter_template_id) REFERENCES public.filter_template(id);


--
-- TOC entry 2922 (class 2606 OID 16489)
-- Name: global_filter_field fk_global_filter_template_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.global_filter_field
    ADD CONSTRAINT fk_global_filter_template_id FOREIGN KEY (global_filter_template_id) REFERENCES public.global_filter_template(id);


-- Completed on 2023-06-30 22:14:53

--
-- PostgreSQL database dump complete
--

