ECA_DB_NAME=eca
ECA_CAMUNDA_DB_NAME=eca_camunda
ECA_OAUTH_DB_NAME=eca_oauth
ERS_DB_NAME=evaluation_results_storage
MAIL_DB_NAME=mail
ECA_DS_DB_NAME=data_storage
ECA_AUDIT_LOG_DB_NAME=audit_log
ECA_WEB_PUSH_DB_NAME=eca_web_push
BACKUPS_FOLDER=backups
psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER <<-EOSQL
    CREATE DATABASE $ECA_DB_NAME;
    CREATE DATABASE $ECA_CAMUNDA_DB_NAME;
	  CREATE DATABASE $ECA_OAUTH_DB_NAME;
	  CREATE DATABASE $ERS_DB_NAME;
    CREATE DATABASE $MAIL_DB_NAME;
    CREATE DATABASE $ECA_DS_DB_NAME;
    CREATE DATABASE $ECA_AUDIT_LOG_DB_NAME;
    CREATE DATABASE $ECA_WEB_PUSH_DB_NAME;
EOSQL
psql $ECA_DB_NAME < $BACKUPS_FOLDER/eca-backup.sql
psql $ECA_OAUTH_DB_NAME < $BACKUPS_FOLDER/eca-oauth-backup.sql
psql $ERS_DB_NAME < $BACKUPS_FOLDER/eca-ers-backup.sql
psql $MAIL_DB_NAME < $BACKUPS_FOLDER/eca-mail-backup.sql
psql $ECA_DS_DB_NAME < $BACKUPS_FOLDER/eca-data-storage-backup.sql
psql $ECA_AUDIT_LOG_DB_NAME < $BACKUPS_FOLDER/eca-audit-log-backup.sql
psql $ECA_WEB_PUSH_DB_NAME < $BACKUPS_FOLDER/eca-web-push-backup.sql